### ISSUE TITLE
Applying controller_config will result to loss registry type, repository name values

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/K8s-api-operator#253]
`kubectl apply -f controller_conf.yaml` will update result to update `registryType` and `repositoryName` values with default.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: controller-config
  namespace: wso2-system
data:
  #docker registry type which the mgw image to be pushed. supported types: DOCKER_HUB, AMAZON_ECR, GCR, PRIVATE.   Default->  registryType: DOCKER_HUB
  registryType: DOCKER_HUB
  #docker repository name which the mgw image to be pushed.  eg->  repositoryName: username of Docker Hub account
  repositoryName: REPOSITORY_NAME_OF_DOCKER_REGISTRY
```
