### ISSUE TITLE
Policy-configmap not updated when ratelimitings are deleted

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/k8s-api-operator#304]
**Description:**
`policy-configmap` not updated when ratelimitings are deleted.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Add a ratelimiting CR
1. Delete the added ratelimiting CR
1. `kubectl get cm policy-configmap -oyaml`

The added ratelimitting is still in the configmap: `policy-configmap`
```yaml
data:
  policies.yaml: |
    resourcePolicies:
    ...
    - fourreqpolicy:
        count: 4
        unitTime: 1
        timeUnit: min
```

**Related Issues:**
