### ISSUE TITLE
Use private docker registries for toolkit and runtime docker images

### ISSUE THREAD

**Issue by pubudu538** [wso2/k8s-api-operator#338]
**Description:**
There are two use cases here.

1. Private docker registry that is not secured with Basic Auth
This is what Renuka has tested.

2. Private docker registry that is secured with Basic Auth
For this, we need to update the Kaniko job with a docker pull secret.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by renuka-fernando** [comment]
**Working fine for HTTP registry secured with Basic Auth (use case 02)**

## Use Case 2: Secured with Basic Auth

### 1.  Create an HTTP registry.
```sh
$ docker run \
  --entrypoint htpasswd \
  registry:2 -Bbn renuka renuka1234 > auth/htpasswd


$ docker run -d \
  -p 5000:5000 \
  --restart=always \
  --name registry-auth \
  -v "$(pwd)"/auth:/auth \
  -e "REGISTRY_AUTH=htpasswd" \
  -e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm" \
  -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd \
  registry:2
```

### 2. Pushe MGW toolkit and runtime images
> 192.168.8.132 is my ip
```sh
docker login 192.168.8.132:5000

docker tag wso2am/wso2micro-gw-toolkit:3.2.0-alpha 192.168.8.132:5000/wso2am/wso2micro-gw-toolkit:3.2.0-alpha
docker tag wso2/wso2micro-gw:3.2.0-alpha 192.168.8.132:5000/wso2/wso2/wso2micro-gw:3.2.0-alpha

docker push 192.168.8.132:5000/wso2am/wso2micro-gw-toolkit:3.2.0-alpha
docker push 192.168.8.132:5000/wso2/wso2/wso2micro-gw:3.2.0-alpha
```

### 3. Change `controller-config`
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: controller-config
  namespace: wso2-system
data:
  #mgw toolkit image to initialize/setup the micro gw project
  mgwToolkitImg: 192.168.8.132:5000/wso2am/wso2micro-gw-toolkit:3.2.0-alpha
  #mgw runtime image to use in the mgw executable
  mgwRuntimeImg: 192.168.8.132:5000/wso2/wso2/wso2micro-gw:3.2.0-alpha
```

### 4. Install API operator
```sh
$ apictl install api-operator --registry-type=HTTP --repository=192.168.8.132:5000/operator-test --username=renuka --password=renuka1234
```

### 5. Create an API
Scenario 2
```sh
$ apictl add api -n petstore-api --from-file=scenarios/scenario-2/swagger.yaml --override
```

### 6. Teste
```sh
$ kubectl get po
NAME                        READY   STATUS    RESTARTS   AGE
petstore-api-kaniko-9wg4d   1/1     Running   0          9s
```

```sh
$ curl -X GET "https://<external IP of LB service>:9095/petstore/v1/pet/55" -H "accept: application/xml" -H "Authorization:Bearer $TOKEN" -k

<?xml version="1.0" encoding="UTF-8" standalone="yes"?><apiResponse><message>Pet not found</message><type>error</type></apiResponse>
```
