### ISSUE TITLE
Image pull secret for kaniko image is not configured

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/k8s-api-operator#451]
**Description:**
Error creating kaniko pod when used in an offline environment. The configured image `<PRIVATE_REGISTRY>/kaniko-project/executor:v0.24.0` can not be pulled.

Related config:  controller-config
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: controller-config
  namespace: wso2-system
data:
  #mgw toolkit image to initialize/setup the micro gw project
  mgwToolkitImg: <PRIVATE_REGISTRY>/wso2am/wso2micro-gw-toolkit:3.2.0-rc2
  #mgw runtime image to use in the mgw executable
  mgwRuntimeImg: <PRIVATE_REGISTRY>/wso2/wso2micro-gw:3.2.0-rc2
  #kaniko image for the kaniko pod which builds the mgw api runtime and pushes to the registry
  kanikoImg: <PRIVATE_REGISTRY>/kaniko-project/executor:v0.24.0
```
