### ISSUE TITLE
Able to template HPA metrics configurations for TargetEndpoint and API

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/k8s-api-operator#489]
It is able to scale backend that is not instrumented with metrics (backends are not exposing metrics) when we use metric type "Object" and refer metrics exposed by the Microgateway. So backend is scaled with metrics exposed by the Microgateway.

In private jet mode if we able to define the API from what the backend should get custom metrics, the above can be achieved. For this, we can use templates for HPA configs.

#### Example:
For API name: {{$.API}}
For TargetEndpoint name: {{$.TargetEndpoint}}

##### Sample Config
**Description:**
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: hpa-configs
  namespace: wso2-system
data:
  targetEndpointMetrics: |
    - type: Object
      object:
        metric:
          name: http_requests_total_value_per_second
        describedObject:
          apiVersion: v1
          kind: Service
          name: {{$.API}}
        target:
          type: Value
          value: 1
```

{{$.API}} will be replaced with the API(s) name which it is referenced.

**Suggested Labels:**
Improvement
