### ISSUE TITLE
Merge k8s-ei-operator functionalities into the k8s-api-operator

### ISSUE THREAD

**Issue by sajithaliyanage** [wso2/k8s-api-operator#497]
**Description:**
$subject

As a part of the APIM 4.0 release effort, we are merging [k8s-ei-operator](https://github.com/wso2/k8s-ei-operator) functionalities with **k8s-api-operator**.  Currently, **k8s-ei-operator** has one CRD as **Integration** and its CR is as follows.

```yaml
apiVersion: wso2.com/v1alpha1
kind: Integration
metadata:
  name: test-integration
spec:
  replicas: 1
  image: sajithaliyanage/k8s-samples:helloservice
  ImagePullSecret: git-secret
  InboundPorts:
   - 8000
   - 8001
  env:
    - name: DEV_ENV_USER_EP
      value: "https://reqres.in/api"
```

**Suggested Labels:**
Type/Improvement
