### ISSUE TITLE
K8 service is not updated when updating an existing deployment.

### ISSUE THREAD

**Issue by sachithKay** [wso2/k8s-api-operator#571]
**Description:**
- Create a deployment with default passthroPort (8290).
- Update the integration_cr.yml to change the passthroPort to 8240.
```
  expose:
    passthroPort: 8240
    inboundPorts:
      - 8010
```

- Deploy the new configuration with with `kubectl apply -f integration_cr.yaml -n wso2-system   `
- Check for the k8 services with `kubectl get services -n wso2-system`.
- The port has not been updated.
- As a workaround, you can delete the entire deployment and redeploy.
