### ISSUE TITLE
Add graceful shutdown command for Integration Pods

### ISSUE THREAD

**Issue by sajithaliyanage** [wso2/k8s-api-operator#577]
**Description:**
$subject. We need to add the below spec to the deployment object. 

```yaml
lifecycle:
  preStop:
    exec:
      command:  ['sh', '-c', '${WSO2_SERVER_HOME}/bin/micro-integrator.sh stop']
```

This spec is important when it comes to scaling down scenarios. 

**Suggested Labels:**
type/improvement
