### ISSUE TITLE
Params and Certs support not available

### ISSUE THREAD

**Issue by pubudu538** [wso2/k8s-api-operator#585]
**Description:**
For an API, params and certs should be able to provided as follows.

```
kubectl create cm params-cm --from-file=./params.yaml

kubectl create cm petstore-cm --from-file=./petstore.zip

kubectl create cm certs-cm --from-file=./certificates

certificates folder contains test.crt, mock.crt, etc
```

```
cat <<EOF | kubectl apply -f -
apiVersion: wso2.com/v1alpha2
kind: API
metadata:
    name: petstore-api
    namespace: default
spec:
    swaggerConfigMapName: petstore-cm
    paramsValues: params-cm
    certsValues: certs-cm
EOF
```

```
cat <<EOF | kubectl apply -f -
apiVersion: wso2.com/v1alpha2
kind: API
metadata:
    name: petstore-api
    namespace: default
spec:
    swaggerConfigMapName: petstore-cm
    paramsValues: foo-cm
EOF
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
