### ISSUE TITLE
Append version of the API twice to access URL when create an API with swagger file and import to APIM

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/k8s-api-operator#590]
**Description:**
$subject

When deployed from swagger directly and publish the API
![image](https://user-images.githubusercontent.com/23183042/116507882-d2095d80-a8dd-11eb-899b-6d51818fa378.png)

When deployed from API-CTL project
![image](https://user-images.githubusercontent.com/23183042/116507852-be5df700-a8dd-11eb-98fc-b57c6c0263cb.png)

**Steps to reproduce:**
1. kubectl create cm petstore-cm --from-literal=swagger="$(curl -k https://petstore.swagger.io/v2/swagger.json)"
2. apictl init petstore --oas https://petstore.swagger.io/v2/swagger.json
3. zip -r petstore.zip petstore/
4. kubectl create cm petstore-cm --from-file petstore.zip
5. Add API
    ```
    cat <<EOF | kubectl apply -f -
    apiVersion: wso2.com/v1alpha2
    kind: API
    metadata:
        name: petstore-api
    spec:
        swaggerConfigMapName: petstore-cm
    EOF
    ```
