### ISSUE TITLE
Support add endpoint certificates to MG deployment

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/k8s-api-operator#596]
**Description:**
Add endpoint certificates to MG deployment

```
Products-v1
├── Meta-information
│   ├── api.yaml
│   ├── endpoint_certificates.yaml
│   └── swagger.yaml
└── api_params.yaml

1 directory, 4 files
```

Sample endpoint_certificates.yaml
```yaml
 -
  hostName: https://localhost:8443
  alias: products
  certificate: MIIE3DCCAsQCCQCUhuOIouUHijANBgkqhkiG9w0BAQsFADAwMRUwEwYDVQQKDAxmb28uY29tIEluYy4xFzAVBgNVBAMMDnByb2R1Y3RzLWh0dHBzMB4XDTIxMDUwNDA2NDY1MFoXDTIyMDUwNDA2NDY1MFowMDEVMBMGA1UECgwMZm9vLmNvbSBJbmMuMRcwFQYDVQQDDA5wcm9kdWN0cy1odHRwczCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBANJbE2Pa930Ic6S8LCPs7pjUoo8TS5rJTMu0R/tLZZgBKtHTXk/oJ1ABSwnDbWAn1aSsnIacrfDR6NJTAn3tzMBd48xgAwetfvfBUhgnK7n1RKBuTsIVIb45BSo/w2T/csqpCDR+V776psN25/hPTz7xBhyZFh6SKq5VakuIscz4YJ+uhtkN3Mq7iRPmxjg7iYc509tdSpDDLLiOmIJibZswJpJSTE3gwX/QBjxND089IVD0aB3RD3U6U49JaHjhPYdaAvG1up+aFeCjOlfMZObdVEIYaqXQXrxcPaL3Id955qWdB2jzM1mtoWAp3KZJF4ol42DAttOFVKR6JzAfT1IPSaPAYyCAwSOTuZKEyfqR8RWk/pFkPn5cka1jToiX5lLkJQpVK4QnYY/I85VodaLV40Ep/6KXC8261vAFQlDiNrfm097qa2uHDwnLUBk5NOTEUNZITP3k7zGicTwUjrKBD0h1jdd+AxHw9Y5wBgRBcuSn9VbWgC1CeXf5kLFz5wBqIj5EU8OYDLF9KnlPL3Vlw55XJxclIgwLYJvERaElr/yvl2joDzOnvjGnZWSoUw2F8CXFskn/KW/fWbcTh/JCkw0luCxJRrHRC3oIofL2Btu9R591Psvrw0i1u1De5TcVuV00bIkeWVBCSA9yRGDMZyyX1TDJY9FTg2t3hfytAgMBAAEwDQYJKoZIhvcNAQELBQADggIBAKfm0vyBWqsROV5T1pMdABJrouEBLc2SB8XFwaqCsqkvSHzEnkO26qYHiQfbK0xSUUhwkU3YHk/h00HOMOkmC5uQqDANn79cu8DQiZQ4ZhVNFqO1tY6OOiEgKchdhR1Ry8ZDvUNCEGijLsmgliskBLh1g0yK+gdqyCeivYs1+5vRSmIpCZaK/9iD53ue3zELsiLZzkphztJiGzpv9l6j6VtgVzxnFgGCAY6+wDdPocUwu+G6Y288z9jyG7WO2/3s+p7iOtg+/3SlX5cXHIhLgr4K43F35IxtxRzAiEfkNrloh2jaG1xgzFLsGg7/hlT9K4G8FVwbTN5FXEGjRMd8jDVmhJ5zeQTSXluNURAvGQG6PBjHpcjDyDxB48czsXHNrrQVSnr7GPbJDLb6Rzhq33UblrbYFA8B0OMHdqcR6z5wQTAqP7pBUPnFcj0RHa07emWZRdnC4SvKFbPMFYtUONjh8E4Ln/JUVmJhEzmDlBsskvRM79h4UV7epd398eQpRoEVSlirf69lyn/h86TvSRYQvwUMbhLgTIOnymywRL90R3CJPMv+eXgxnkiv+obmrDg/31Wg1nqK1ETmiZZWsMxN+RxGw6oqajNjKeezf06tN57JDdHuHqS9mkuBgp9VeKcQzEONyLiNgshpnBpQ9/jc7CnqrOX4Rc/1EU5SR3u5
```

**Affected Product Version:**
API Operator 1.2.2

**Proposed Solution**
- APICTL should support to read this `endpoint_certificates.yaml` and create a secret.
- Refer the secret in API CR (new optional field should support this).
- Add the cert through keytool.
